// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdMJHPJ9AOdr0t50_3DEkfYtityJgsn6Y',
    appId: '1:640108505954:web:6be484db839f223b8a5a3b',
    messagingSenderId: '640108505954',
    projectId: 'notes-a4b6d',
    authDomain: 'notes-a4b6d.firebaseapp.com',
    storageBucket: 'notes-a4b6d.appspot.com',
    measurementId: 'G-RF15JNE1H3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkxfZc746Oo8WzGF329fEqOV1dYrkbidc',
    appId: '1:640108505954:android:37dffad259511b098a5a3b',
    messagingSenderId: '640108505954',
    projectId: 'notes-a4b6d',
    storageBucket: 'notes-a4b6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM86Kfui5DfCejrqMgswTqS3tKg9Y551U',
    appId: '1:640108505954:ios:b43bcae37c62e58d8a5a3b',
    messagingSenderId: '640108505954',
    projectId: 'notes-a4b6d',
    storageBucket: 'notes-a4b6d.appspot.com',
    androidClientId: '640108505954-a4l2ihuobq7fptjl3i4sg9ikpe6bfa2o.apps.googleusercontent.com',
    iosClientId: '640108505954-i48p9rc6gcmf6hcn0fithrv82acl499b.apps.googleusercontent.com',
    iosBundleId: 'com.example.inEgypt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM86Kfui5DfCejrqMgswTqS3tKg9Y551U',
    appId: '1:640108505954:ios:b43bcae37c62e58d8a5a3b',
    messagingSenderId: '640108505954',
    projectId: 'notes-a4b6d',
    storageBucket: 'notes-a4b6d.appspot.com',
    androidClientId: '640108505954-a4l2ihuobq7fptjl3i4sg9ikpe6bfa2o.apps.googleusercontent.com',
    iosClientId: '640108505954-i48p9rc6gcmf6hcn0fithrv82acl499b.apps.googleusercontent.com',
    iosBundleId: 'com.example.inEgypt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdMJHPJ9AOdr0t50_3DEkfYtityJgsn6Y',
    appId: '1:640108505954:web:b8c6edf327ba35068a5a3b',
    messagingSenderId: '640108505954',
    projectId: 'notes-a4b6d',
    authDomain: 'notes-a4b6d.firebaseapp.com',
    storageBucket: 'notes-a4b6d.appspot.com',
    measurementId: 'G-04Z151WG0C',
  );
}
